### ISSUE TITLE
Alert success dosen't look great

### ISSUE THREAD

**Issue by FelixINX** [Pingendo/pingendo-bootstrap#10]
Is difficult to see the text of the alert.

![pingendo bootstrap alert](https://cloud.githubusercontent.com/assets/8009156/7554293/09370588-f6f0-11e4-99a4-87dc737f1c78.png)

I think that the text should be more darker.

**Comment by dhqcz** [comment]
Yesterday I also thought. :D

.alert-success {
  color: #1B6A1B !important;
}

**Comment by FelixINX** [comment]
I will make a pull request. Thanks
