### ISSUE TITLE
Stuck on Update Screen

### ISSUE THREAD

**Issue by ghostzero192** [Pingendo/pingendo-bootstrap#15]
Hi, first of all i have been checking pingendo and i think is a great program, thanks to the people behind its creation, i downloaded the version v0.33.1 for windows from http://www.pingendo.com/, for use it offline (no internet), here is my problem if my computer is not connected to anything (local networks or virtual machines etc) the program works fine, but as soon im connected to something even if it does not have internet access, the program just shows me that is looking for updates and does nothing else

**Comment by gseregni** [comment]
@ghostzero192 we are aware of the the problems about update and offline story.
For this reason in the upcoming 4.0 version we'll use the standard HTML5 cache system. For the current version no fixes are planned at the moment. Sorry.

**Comment by ghostzero192** [comment]
@gseregni well at least i can use it while i wait for version 4.0, thanks for the answer.

**Comment by gseregni** [comment]
@ghostzero192 you can test an alpha of Pingendo 4 at http://v4.pingendo.com/playground.html
